version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  frontend:
    # image: node:10.15.1
    build:
      context: .
      dockerfile: ./compose/local/nuxt/Dockerfile
    image: todo_app_local_nuxt
    container_name: nuxt
    volumes:
      - .:/nuxt:z
    ports:
      - "3000:3000"
    env_file:
      - ./.envs/.local/.nuxt

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: todo_app_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: todo_app_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  # docs:
  #   image: todo_app_local_docs
  #   container_name: docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./todo_app:/app/todo_app:z
  #   ports:
  #     - "7000:7000"
  #   command: /start-docs
